comparison_id: diginetica_popular_source_methods_sample10_creat_no_pos0

runs:
  - diginetica_clean_popular_source_methods_sample10_creat_no_pos0
  - diginetica_randomnz_popular_source_methods_sample10_creat_no_pos0
  - diginetica_generated_direct_cem_popular_source_methods_sample10_creat_no_pos0
  - diginetica_copy_direct_cem_popular_source_methods_sample10_creat_no_pos0
  - diginetica_creat_no_pos0_popular_source_methods_sample10
