comparison_id: formal_6method6victim_all
slice_compatibility: relaxed_debug
runs:
  - formal_5method6victim_diginetica_clean_popular_sample10
  - formal_5method6victim_diginetica_randomnz_popular_sample10
  - formal_5method6victim_diginetica_generated_direct_cem_popular_sample10
  - formal_5method6victim_diginetica_copy_direct_cem_popular_sample10
  - formal_5method6victim_diginetica_creat_popular_sample10
  - formal_6method6victim_diginetica_poisoning_ssl_sbr_popular_sample10
  - formal_5method6victim_diginetica_clean_unpopular_sample10
  - formal_5method6victim_diginetica_randomnz_unpopular_sample10
  - formal_5method6victim_diginetica_generated_direct_cem_unpopular_sample10
  - formal_5method6victim_diginetica_copy_direct_cem_unpopular_sample10
  - formal_5method6victim_diginetica_creat_unpopular_sample10
  - formal_6method6victim_diginetica_poisoning_ssl_sbr_unpopular_sample10
  - formal_5method6victim_yoochoose1_64_clean_popular_sample10
  - formal_5method6victim_yoochoose1_64_randomnz_popular_sample10
  - formal_5method6victim_yoochoose1_64_generated_direct_cem_popular_sample10
  - formal_5method6victim_yoochoose1_64_copy_direct_cem_popular_sample10
  - formal_5method6victim_yoochoose1_64_creat_popular_sample10
  - formal_6method6victim_yoochoose1_64_poisoning_ssl_sbr_popular_sample10
  - formal_5method6victim_yoochoose1_64_clean_unpopular_sample10
  - formal_5method6victim_yoochoose1_64_randomnz_unpopular_sample10
  - formal_5method6victim_yoochoose1_64_generated_direct_cem_unpopular_sample10
  - formal_5method6victim_yoochoose1_64_copy_direct_cem_unpopular_sample10
  - formal_5method6victim_yoochoose1_64_creat_unpopular_sample10
  - formal_6method6victim_yoochoose1_64_poisoning_ssl_sbr_unpopular_sample10
