comparison_id: yoochoose1_64_popular_source_methods_sample10_creat_no_pos0

runs:
  - yoochoose1_64_clean_popular_source_methods_sample10_creat_no_pos0
  - yoochoose1_64_randomnz_popular_source_methods_sample10_creat_no_pos0
  - yoochoose1_64_generated_direct_cem_popular_source_methods_sample10_creat_no_pos0
  - yoochoose1_64_copy_direct_cem_popular_source_methods_sample10_creat_no_pos0
  - yoochoose1_64_creat_no_pos0_popular_source_methods_sample10
