comparison_id: yoochoose1_64_unpopular_source_methods_sample10

runs:
  - yoochoose1_64_clean_unpopular_source_methods_sample10
  - yoochoose1_64_randomnz_unpopular_source_methods_sample10
  - yoochoose1_64_generated_direct_cem_unpopular_source_methods_sample10
  - yoochoose1_64_copy_direct_cem_unpopular_source_methods_sample10
