style_name: default_slide_png

output_format: png

input_dir: results\comparisons\dpsbr_vs_random_nonzero_when_possible_diginetica_popular_0.1size\attack_vs_victim_metrics_largeK_11169

title:
  template: "Diginetica_attackSize0.1_popularTargets_metrics_11169_largeK_comparison"
  align: center
  font_size: 12
  color: black

figure:
  width: 14
  height: 6
  dpi: 220
  background_color: white

table:
  font_size: 12
  round_digits: 6
  text_color: black
  show_grid: true
  auto_shrink: false
  wrap_text: false
  cell_align: center
  display_alias:
    "attack_method": "Attack"
  value_alias:
    attack_method:
      dpsbr_baseline: "DPSBR"
      random_nonzero_when_possible: "RandomNo0"
