from __future__ import annotations

import pytest

from attack.common.paths import (
    CREAT_ADDITIVE_SBR_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_GENERATED_CONTINUATION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_TRUNCATE_SUFFIX_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_REPLACEMENT_GENERATED_CONTINUATION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_REPLACEMENT_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    POPULAR_ANCHOR_INTERNAL_CONSTRUCTION_RUN_TYPE,
    POSITION_OPT_RANK_BUCKET_CEM_CANDIDATE_REPLAY_RUN_TYPE,
    POSITION_OPT_RANK_BUCKET_CEM_RUN_TYPE,
    POSITION_OPT_SHARED_POLICY_RUN_TYPE,
    PREFIX_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    PTS_CONSTRUCTION_CANDIDATE_REPLAY_RUN_TYPE,
    PTS_CONSTRUCTION_DIRECT_ACTION_MLP_CEM_RUN_TYPE,
    PTS_CONSTRUCTION_GROUPED_CEM_RUN_TYPE,
    RANDOM_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    RANDOM_INSERTION_THEN_CROP_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TAIL_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TAIL_REPLACEMENT_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TARGET_AWARE_CARRIER_LOCAL_POSITION_RUN_TYPE,
    TARGET_AWARE_CARRIER_SELECTION_NZ_RUN_TYPE,
    TARGET_AWARE_COVERAGE_LOCAL_POSITION_RUN_TYPE,
    VULNERABLE_ANCHOR_INTERNAL_CONSTRUCTION_RUN_TYPE,
    classify_victim_training_run_type,
)
from attack.position_opt.bucket_selector import BUCKET_METHODS


POISONED = (
    "always_pos0", "dpsbr_baseline", "random_nonzero_when_possible",
    CREAT_ADDITIVE_SBR_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_GENERATED_CONTINUATION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_INSERTION_TRUNCATE_SUFFIX_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_REPLACEMENT_GENERATED_CONTINUATION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    INTERNAL_RANDOM_REPLACEMENT_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    POPULAR_ANCHOR_INTERNAL_CONSTRUCTION_RUN_TYPE,
    POSITION_OPT_RANK_BUCKET_CEM_CANDIDATE_REPLAY_RUN_TYPE,
    POSITION_OPT_RANK_BUCKET_CEM_RUN_TYPE, POSITION_OPT_SHARED_POLICY_RUN_TYPE,
    PREFIX_NONZERO_WHEN_POSSIBLE_RUN_TYPE, PTS_CONSTRUCTION_CANDIDATE_REPLAY_RUN_TYPE,
    PTS_CONSTRUCTION_DIRECT_ACTION_MLP_CEM_RUN_TYPE,
    PTS_CONSTRUCTION_GROUPED_CEM_RUN_TYPE,
    RANDOM_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    RANDOM_INSERTION_THEN_CROP_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TAIL_INSERTION_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TAIL_REPLACEMENT_NONZERO_WHEN_POSSIBLE_RUN_TYPE,
    TARGET_AWARE_CARRIER_LOCAL_POSITION_RUN_TYPE,
    TARGET_AWARE_CARRIER_SELECTION_NZ_RUN_TYPE,
    TARGET_AWARE_COVERAGE_LOCAL_POSITION_RUN_TYPE,
    VULNERABLE_ANCHOR_INTERNAL_CONSTRUCTION_RUN_TYPE,
    *BUCKET_METHODS,
)


def test_all_audited_production_run_types_classify():
    assert classify_victim_training_run_type("clean") == "clean"
    assert all(classify_victim_training_run_type(value) == "poisoned" for value in POISONED)


@pytest.mark.parametrize(
    "value",
    ["victim_valbest_epoch_diagnostic", "creat_additive_sbr_generate_only",
     "surrogate_diagnostic_only", "srgnn_checkpoint_eval", "attack",
     "position_opt_mvp", "unknown"],
)
def test_non_training_run_types_are_rejected(value):
    assert classify_victim_training_run_type(value) == "unsupported"
